name: build-docs
on:
  push:
    branches:
      - stable
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install  Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[docs]
      - name: Build Docs
        run: |
          git config --local user.email "hakancelikdev@gmail.com"
          git config --local user.name "Hakan Celik"
          git fetch --all
          mkdocs gh-deploy -m "Update Docs" --remote-branch gh-pages
