name: pre-commit
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-python@v2.3.3
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install dependencies for pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: pre-commit
        run: |
          tox -e pre-commit
