name: publish-package-on-pypi
on:
  push:
    tags:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-python@v2.3.3
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install  Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
      - run: python -m build
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-python@v2.3.3
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install  Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
      - run: python -m build
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
