name: test
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2.5.0

      - name: Set up Python${{ matrix.python-version }}
        uses: actions/setup-python@v2.3.3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install  Dependencies for Python${{ matrix.python-version }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Test with pytest for Python${{ matrix.python-version }}
        run: |
          tox -e ${{ matrix.python-version }}
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0

      - name: Set up Python3.10
        uses: actions/setup-python@v2.3.3
        with:
          python-version: "3.10"
          architecture: x64

      - name: Install  Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[tests]
      - name: Generate coverage report
        run: |
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{secrets.CODECOV_TOKEN }}
          verbose: true
          files: ./coverage.xml
